### ISSUE TITLE
Django-Defender with custom user model

### ISSUE THREAD

**Issue by zitrolmo** [kencochrane/django-defender#43] opened 2015-06-16 11:25 UTC
I have Django-Defender installed and apparently working, but it does not register bad login attempts in the DB. Redis is also running. I think this may be caused by the employment of a custom user model. Is there any way of configuring Django-Defender so that I can tell the package which is my User model? Thanks

**Comment by kencochrane** [comment] 2015-06-16 12:30
@zitrolmo 

We don't do anything with the User Model, we just store the username that is used in the login attempt.

Does your login form use a field other then ``username``? If so, you will need to set the ``DEFENDER_USERNAME_FORM_FIELD`` setting to include the name of your field.

does it register any login attempts in the database? or only valid ones? Do you have the setting ``DEFENDER_STORE_ACCESS_ATTEMPTS`` set to True? It is defaulted to True if it isn't set.

If you are using Celery ``DEFENDER_USE_CELERY`` = True, then do you have a celery worker running?

**Comment by zitrolmo** [comment] 2015-06-16 14:19
Dear Ken,

thank you so much for your soon response.

This is my login view:

# _______ LOGIN - LOGOUT _______ 
def userLogin(request):
	if request.method == "POST":
		if 'login_form' in request.POST:
			usuario = request.POST.get('username', '')
			password = request.POST.get('password', '')
			user = authenticate(username=usuario, password=password)
			if user is not None:
				if user.is_active:
					login(request, user) # Logueamos
					if not request.POST.get('rememberUser', None): 
						request.session.set_expiry(3600) 
					return redirect(‘main_app:index')
				else:
					return redirect('users_app:disabled_account') # TODO Return a 'disabled account' error message
			else:
				return redirect('users_app:login_failed')
	return redirect(‘main_app:index')


def LogOut(request):
	logout(request)
	return redirect('/')


As you can see, the form field is called “username”. I’m not using Celery yet.

The behavior is the following: nothing is being registered in the database, neither the valid logins nor the bad ones :(.

I don’t know what else can I do.

Thank you very much for your help. I really appreciate it.

--Juan

**Comment by kencochrane** [comment] 2015-06-16 14:26
@zitrolmo Do you have the defender app in your INSTALLED_APPS, and did you either add the defender middleware, or the login decorator around your login method?

**Comment by zitrolmo** [comment] 2015-06-16 14:29
Right, I have the ‘defender’ app and the ‘defender.middleware.FailedLoginMiddleware’. What I did not include was the login decorator around the login method. Is it like the watch_login() in django-axes? I did not see anything about it in the docs :(

**Comment by kencochrane** [comment] 2015-06-16 14:32
@zitrolmo you normally don't need the decorator if you are using the middleware, but if you are doing some custom login stuff, then you will need the login decorator.  It is usually one or the other. 

If the middleware isn't working, try the login decorator, to see if that starts to work, if so, then you can either keep that, or work backwards to find out why the middleware doesn't work but the login decorator does.

**Comment by zitrolmo** [comment] 2015-06-16 14:39
Dear Ken, still not working having @watch_login before the login view, and also surrounding in the urls.py file as follows:

url(r'^login/$', watch_login(userLogin), name="login”),

I’ve tried also removing the line of the middleware.

**Comment by kencochrane** [comment] 2015-06-16 14:47
Hmm, that is odd, are you seeing any errors in the logs? what settings are you using for django defender?

**Comment by zitrolmo** [comment] 2015-06-16 14:53
Yes, I have no idea about what’s wrong.

I’m just using this option:
DEFENDER_STORE_ACCESS_ATTEMPTS = True

By the way, where can I find the logs? I’m using the development server of Django right now, and I didn’t know about saving error logs to a file on it.

Thanks

**Comment by zitrolmo** [comment] 2015-06-16 15:28
I have removed the @watch_login decorator that I had before the login view in the views.py file, and now it is storing the access attempts in the table. However, it says that all logins were valid, while they were not.

Any idea?

Thank you.

**Comment by kencochrane** [comment] 2015-06-16 20:51
@zitrolmo that is odd, I wonder why it isn't working correctly for you. Are you doing anything weird with an invalid login? 

This is what the code is expecting:
https://github.com/kencochrane/django-defender/blob/master/defender/decorators.py#L29-L33

Your code looks like it does a redirect if they get it wrong, which is unusual (normally you return an error, and not do a redirect), and maybe the cause. 

```
return redirect('users_app:login_failed')
```

Example from django docs: https://docs.djangoproject.com/en/1.8/topics/auth/default/#how-to-log-a-user-in

**Comment by zitrolmo** [comment] 2015-06-16 21:05
Wow! That’s the problem! I’ve replaced that sentence by this one:

return HttpResponse("Error”)

Now it is detecting failed logins! Awesome! 

What I need now is to redirect to the failed login attempt page, but I don’t know how to do it in order to keep working django-defender correctly.

Thank you for everything!

**Comment by kencochrane** [comment] 2015-06-16 21:18
Instead of redirecting just return the failed login page in the response instead of ERROR, and you should be good. Or just return an error, and use the same login form, with the error message in it.

**Comment by zitrolmo** [comment] 2015-06-16 21:31
Now it is working perfectly! Thank you so much. The crucial point here was the redirection, which returns a 302 code, and then it does not permit django-defender to detect failed logins properly.

Best regards and let me thank you again for your contribution and also for your help.

**Comment by kencochrane** [comment] 2015-06-16 21:34
@zitrolmo glad you got it working, going to close this issue.

**Closed by kencochrane** 2015-06-16 21:34 UTC
